psychomot_index:
    path:     /
    defaults: { _controller: "PsychomotBundle:Psychomot:index" }
    methods:  GET

psychomot_show:
    path:     /{id}/show
    defaults: { _controller: "PsychomotBundle:Psychomot:show" }
    methods:  GET

psychomot_new:
    path:     /new
    defaults: { _controller: "PsychomotBundle:Psychomot:new" }
    methods:  [GET, POST]

psychomot_edit:
    path:     /{id}/edit
    defaults: { _controller: "PsychomotBundle:Psychomot:edit" }
    methods:  [GET, POST]

psychomot_delete:
    path:     /{id}/delete
    defaults: { _controller: "PsychomotBundle:Psychomot:delete" }
    methods:  DELETE

psychomot_redirection:
    path:     /redirection
    defaults: { _controller: "SiteBundle:Default:redirection" }
    methods:  DELETE

psychomot_mail:
    path:     /
    defaults: { _controller: "PsychomotBundle:Psychomot:mail" }
