<?php

namespace PsychomotBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PsychomotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PsychomotRepository extends EntityRepository
{
}
