PsychomotBundle\Entity\Psychomot:
    type: entity
    table: null
    repositoryClass: PsychomotBundle\Repository\PsychomotRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        tel:
            type: string
            length: '14'
        titleDef:
            type: string
            length: 255
            column: title_def
        txtDef:
            type: string
            length: 255
            column: txt_def
        titleWho:
            type: string
            length: 255
            column: title_who
        txtWho:
            type: string
            length: 255
            column: txt_who
        titleWhy:
            type: string
            length: 255
            column: title_why
        txtWhy:
            type: string
            length: 255
            column: txt_why
        titlePsy:
            type: string
            length: 255
            column: title_psy
        txtPsy1:
            type: string
            length: 255
            column: txt_psy1
        txtPsy2:
            type: string
            length: 255
            column: txt_psy2
        titleConsult:
            type: string
            length: 255
            column: title_consult
        txtConsult:
            type: string
            length: 1000
            column: txt_consult
        titleInterv:
            type: string
            length: 255
            column: title_interv
        txtInterv:
            type: string
            length: 1000
            column: txt_interv
        titleBilan:
            type: string
            length: 255
            column: title_bilan
        txtBilan:
            type: string
            length: 1000
            column: txt_bilan
        namePsy1:
            type: string
            length: 255
            column: name_psy1
        namePsy2:
            type: string
            length: 255
            column: name_psy2
        contactAdress:
            type: string
            length: 255
            column: contact_adress
        contactMail:
            type: string
            length: 255
            column: contact_mail
        contactTel:
            type: string
            length: 255
            column: contact_tel
        contactName:
            type: string
            length: 255
            column: contact_name
    lifecycleCallbacks: {  }
